#!/usr/bin/env python3
"""Build the main paper results table from the n=80 Gaussian-copula full run.

Uses the Part II validation metrics only:
  LIWC: MAE_LIWC, ρ_LIWC, β_LIWC
  Embedding: ρ_O, ρ_N

Intentionally excludes archived tertile metrics (Self-ID%, Cell CV, Avg).
"""

from __future__ import annotations

import sys
from pathlib import Path

_OPTIMIZED_DIR = Path(__file__).resolve().parents[1]
if str(_OPTIMIZED_DIR) not in sys.path:
    sys.path.insert(0, str(_OPTIMIZED_DIR))

import pandas as pd

from common import FULL_RESULTS_DIR, ensure_results_dir

CONDITION_LABELS = {
    "persona_only": "Persona",
    "liwc_only": "LIWC-only",
    "persona_liwc": "Persona+LIWC",
    "lex_fewshot": "LIWC+Fewshot",
}
CONDITION_ORDER = list(CONDITION_LABELS.keys())

MODEL_LABELS = {
    "deepseek-v3": "DeepSeek-V3",
    "gpt-4o-mini": "GPT-4o-mini",
    "qwen3-32b": "Qwen3-32B",
}
MODEL_ORDER = list(MODEL_LABELS.keys())


def _fmt(value: float, digits: int = 2) -> str:
    if value != value:
        return "--"
    rounded = round(value, digits)
    if rounded < 0:
        return f"$-${abs(rounded):.{digits}f}"
    return f"{rounded:.{digits}f}"


def _best_mask(series: pd.Series, *, higher_is_better: bool) -> list[bool]:
    vals = series.to_numpy(dtype=float)
    if higher_is_better:
        # Calibration: closest to 1 wins.
        if series.name == "beta_LIWC":
            score = -abs(vals - 1.0)
            best = float(score.max())
            return [abs(s - best) < 1e-12 for s in score]
        best = float(vals.max())
        return [abs(v - best) < 1e-12 for v in vals]
    best = float(vals.min())
    return [abs(v - best) < 1e-12 for v in vals]


def load_metrics(
    *,
    liwc_path: Path,
    emb_path: Path,
) -> pd.DataFrame:
    liwc = pd.read_csv(liwc_path)
    liwc = liwc[liwc["model_key"] != "ALL"].copy()
    emb = pd.read_csv(emb_path)
    emb_o = emb[emb["trait"] == "O"][
        ["model_key", "steering_condition", "rho"]
    ].rename(columns={"rho": "rho_O"})
    emb_n = emb[emb["trait"] == "N"][
        ["model_key", "steering_condition", "rho"]
    ].rename(columns={"rho": "rho_N"})
    out = liwc.merge(emb_o, on=["model_key", "steering_condition"], how="left")
    out = out.merge(emb_n, on=["model_key", "steering_condition"], how="left")
    out = out.rename(
        columns={
            "mean_standardized_mae": "MAE_LIWC",
            "mean_category_rho": "rho_LIWC",
            "mean_category_slope": "beta_LIWC",
        }
    )
    out["method"] = out["steering_condition"].map(CONDITION_LABELS)
    out["model"] = out["model_key"].map(MODEL_LABELS)
    out["steering_condition"] = pd.Categorical(
        out["steering_condition"], categories=CONDITION_ORDER, ordered=True
    )
    out["model_key"] = pd.Categorical(
        out["model_key"], categories=MODEL_ORDER, ordered=True
    )
    return out.sort_values(["model_key", "steering_condition"]).reset_index(drop=True)


def bold_within_model(df: pd.DataFrame) -> pd.DataFrame:
    marked = df.copy()
    metric_cols = (
        ("MAE_LIWC", False),
        ("rho_LIWC", True),
        ("beta_LIWC", True),
        ("rho_O", True),
        ("rho_N", True),
    )
    for col, _ in metric_cols:
        marked[f"best_{col}"] = False
    for _, grp_idx in marked.groupby("model_key", observed=True).groups.items():
        idx = list(grp_idx)
        sub = marked.loc[idx]
        for col, higher in metric_cols:
            flags = _best_mask(sub[col].rename(col), higher_is_better=higher)
            marked.loc[idx, f"best_{col}"] = flags
    return marked


def write_csv(df: pd.DataFrame, path: Path) -> None:
    cols = [
        "model",
        "method",
        "MAE_LIWC",
        "rho_LIWC",
        "beta_LIWC",
        "rho_O",
        "rho_N",
        "n_authors",
    ]
    df[cols].to_csv(path, index=False)


def write_fragment(df: pd.DataFrame, path: Path) -> None:
    lines = [
        "% Auto-generated by optimized/runners/build_paper_table.py",
        "% Metrics: MAE_LIWC, rho_LIWC, beta_LIWC, emb rho_O / rho_N",
        "% Excludes Self-ID%, Cell CV, and Avg composites.",
        r"\begin{table*}[t]",
        r"\centering",
        r"\footnotesize",
        r"\renewcommand{\arraystretch}{1.05}",
        r"\setlength{\tabcolsep}{10pt}",
        r"\begin{tabular}{@{}lccccc@{}}",
        r"\toprule",
        r" & \multicolumn{3}{c}{LIWC alignment} & \multicolumn{2}{c}{Emb.\ recovery} \\",
        r"\cmidrule(lr){2-4} \cmidrule(lr){5-6}",
        (
            r"Method & $\mathrm{MAE}_{\mathrm{LIWC}}\downarrow$ & "
            r"$\rho_{\mathrm{LIWC}}\uparrow$ & "
            r"$\beta_{\mathrm{LIWC}}{\approx}1$ & "
            r"$\rho_O\uparrow$ & $\rho_N\uparrow$ \\"
        ),
        r"\midrule",
    ]

    for model_key in MODEL_ORDER:
        label = MODEL_LABELS[model_key]
        lines.append(rf"\multicolumn{{6}}{{c}}{{{label}}} \\")
        lines.append(r"\midrule")
        sub = df[df["model_key"] == model_key]
        for _, row in sub.iterrows():
            cells = []
            for col, digits in (
                ("MAE_LIWC", 2),
                ("rho_LIWC", 2),
                ("beta_LIWC", 2),
                ("rho_O", 2),
                ("rho_N", 2),
            ):
                text = _fmt(float(row[col]), digits=digits)
                if bool(row.get(f"best_{col}", False)):
                    text = rf"\textbf{{{text}}}"
                cells.append(text)
            lines.append(f"{row['method']} & " + " & ".join(cells) + r" \\")
        if model_key != MODEL_ORDER[-1]:
            lines.append(r"\midrule")

    n = int(df["n_authors"].iloc[0]) if len(df) else 80
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            (
                rf"\caption{{Main results by model and steering method "
                rf"($n{{=}}{n}$ authors per cell). "
                r"LIWC metrics are author-level (six topics concatenated, then re-scored). "
                r"$\mathrm{MAE}_{\mathrm{LIWC}}\downarrow$ is standardised absolute error. "
                r"$\rho_{\mathrm{LIWC}}\uparrow$ is mean category Spearman tracking. "
                r"$\beta_{\mathrm{LIWC}}{\approx}1$ is calibration "
                r"(values above 1 indicate overshoot). "
                r"Emb.\ $\rho_O$/$\rho_N\uparrow$ is Ridge probe recovery.}}"
            ),
            r"\label{tab:continuous-full}",
            r"\end{table*}",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    tables_dir = ensure_results_dir(FULL_RESULTS_DIR / "tables")
    liwc_path = FULL_RESULTS_DIR / "generations" / "full_author_condition_model_summary.csv"
    emb_path = FULL_RESULTS_DIR / "embedding" / "embedding_author_summary.csv"
    df = load_metrics(liwc_path=liwc_path, emb_path=emb_path)
    df = bold_within_model(df)
    csv_path = tables_dir / "full_results_paper_table.csv"
    frag_path = tables_dir / "full_results_paper_table_fragment.tex"
    write_csv(df, csv_path)
    write_fragment(df, frag_path)
    print(f"Wrote {csv_path}")
    print(f"Wrote {frag_path}")
    print(df[["model", "method", "MAE_LIWC", "rho_LIWC", "beta_LIWC", "rho_O", "rho_N"]].to_string(index=False))


if __name__ == "__main__":
    main()
